pages/reference.html

This fixes the below error when running `yarn dev`: 
```
Server running at http://localhost:1234
🚨  /Users/mindy/Desktop/mdn-minimalist/pages/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach: ENOENT: no such file or directory, open '/Users/mindy/Desktop/mdn-minimalist/pages/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach'
Error: ENOENT: no such file or directory, open '/Users/mindy/Desktop/mdn-minimalist/pages/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach'
``` 
I think Parcel has issue with not being able to find anything at the referenced URL.

Remove relative URLs from all anchor tags  

---

sass/atoms/_icons.scss
sass/atoms/_links.scss

The width and height added to icon-base breaks icon buttons. Move
width and height to instances of links with icons.
fix #36

(fix) bug between icon buttons and links

---

sass/atoms/_icons.scss

No need for the `background-color: transparent;` rule on `.icon-base`
fix #38

(fix) collision with icon buttons and links

---

sass/atoms/_buttons.scss

Do not attach base style rules to elements directly. This will more
often than not cause the need for a lot of overrides in code that uses
this base framework. In general prefer the use of classes.
fix #45

(fix) do not attach style to button element

---

sass/atoms/_buttons.scss

Add style for ghost buttons. This removes the basic default
browser styles for button elements such as:
- `background-color`
- `border`
and adds `cursor: pointer;`
fix #48

(enhancement) ghost button

---

sass/atoms/_buttons.scss

Inactive buttons should have its cursor set to default.
fix #62

(fix) inactive button state

---

.prettierignore
sass/grid/_reference.scss

Update to reference page grid. This also removes the slot for the
footer newsletter
fix #76 fix #75

(breaking) new grid for reference pages

---

sass/atoms/_typography.scss

Reference font files using relative paths
fix #80

(fix) relative paths for fonts

---

sass/grid/_reference.scss

The reference page grid incorrectly places the sidebar below the footer on mobile.
fix #84

reference page grid for mobile incorrect

---

sass/atoms/_forms.scss

Set background-color to transparent for `code` elements inside a highlighted `legend`
Remove additional left padding from highlighted `legend` elements
fix #134

fix: forms

---

sass/grid/_reference.scss

Update the reference page grid to account for the language selector component.
This does mean that the class names need to be updated.
`breadcrumb-locale-container` becomes `breadcrumb-container` and there is a new `locale-container`
fix #139

breaking: update reference page grid - locale container

---

.stylelintignore
sass/shared-variables.scss
webpack.config.js

Add a shared variables file that enables sharing of specific variables between SASS and JS without impacting the minimalist CSS.
fix #64

create shared variables file

---

sass/vars/_layout.scss

Add `z-index` scale. This scale should always be used over a hard coded `z-index` value
fix #164

z-index scale

---

sass/atoms/_code.scss
sass/atoms/_typography.scss
sass/mdn-minimalist.scss

`code` elements inside syntax highlighted code examples should not have a background color set.
fix #182

code element in prism blocks

---

sass/vars/_typography.scss

Add `$code-example-line-height: 1.4;`
fix #196

add code examples line height variable

---

.github/workflows/release-please.yml

Instead of doing `npm ci` in release-please use `yarn install --frozen-lockfile`

fix: use yarn not npm

---

sass/atoms/_tables.scss

Adjust the max width of the first header cell to avoid overflow on mobile

fix: adjust first header cell max width

---

sass/vars/_typography.scss

Switch to a major third typescale aka 1.250 with a base of 18px
fix #229

fix: new desktop typescale

---

sass/vars/_typography.scss

Respect the users base font size preference and use a 100% for the base font size instead of a pixel value.
fix #237

fix: use 100% for base font size

---

sass/grid/_standard.scss

Add default padding to `page-content-container` for standard page grid

fix: default padding for standard grid

---

sass/atoms/_links.scss
sass/atoms/_meta.scss
sass/atoms/_tables.scss
sass/vars/_color-palette.scss

Change the background color of standard tables to better accommodate various colors of text and iconography
fix #259
Add basic styling for in content tables that have no class attribute.
fix #264
Avoid overlapping text and unwanted overflow with the bulk of tables
fix #259

table updates

---

sass/atoms/_base.scss

Avoid img scaling issues by adding `height: auto;` to `_base.scss`
fix #278

fix: img sizing

---

sass/atoms/_callout.scss

Use Zilla for h3 heading in callouts but without the background slab
fix #277

fix: no-slab h3 callouts

---

sass/atoms/_notecards.scss

Use `font-weight: normal;` for inline notecards
fix #269

fix: inline notecards should use normal font-weight

---

sass/atoms/_code.scss

Give `kbd` elements a little more space, especially when used inside a `table` element
fix #267

fix: give kbd element a little more space

---

sass/atoms/_tables.scss

Set background color for `pre` elements inside a `table` element to white
fix #268

fix: code element in tables

---

sass/atoms/_code.scss

It makes more sense for the general styling of `pre` elements to live alongside custom styles such as "good" and "bad" variants.
fix #294

fix: move pre styling to minimalist

---

sass/atoms/_icons.scss

Ensure icons align correctly when used in heading elements
fix #298

fix: icons in headings

---

sass/atoms/_code.scss
sass/vars/_typography.scss

Explicitly set the font size for code example to ensure it is always rendered at a minimum of `1rem`
fix #299

fix: font size for code examples

---

sass/atoms/_notecards.scss

To better accomodate cases where a notecard is the first item in an article, we
set the top margin to `$base-spacing / 2`
fix #303

fix: change top margin for notecards

---

sass/atoms/_tables.scss

To accomodate a recent change with regards to margins in articles,
we need to add a bottom margin to tables.
fix #305

fix: add bottom margin to tables

---

sass/atoms/_links.scss
sass/atoms/_tables.scss
sass/vars/_color-palette.scss

Use `primary-50` for _all_ links. Better contrast, better legibility, more consistency
fix #313

fix: improved link color

---

package.json

When I tried to run the project for the first time I didn't have a public folder so the copy command failed. So I have updated the yarn copy command to make a public directory if it doesn't exist. :)

Update yarn copy to make public directory if it does not exist

---

sass/atoms/_notecards.scss

If a notecard does not have an `h4` heading, do not show an icon
fix #316

fix: no heading no icon - notecards

---

sass/mixins/_links.scss
test/sass/_test-mixins-links.scss

Update background color for `highlighted-link-state` to `$primary-50`
fix #317

fix: highlighted link state

---

sass/grid/_document.scss
sass/mdn-minimalist.scss

Add section for metadata row to grid
Rename `reference-page` to `document-page`
Add style for `no-sidebar`
fix #335

fix: add metadata grid section

---

sass/atoms/_primsjs.scss

Updates the operator, entity etc. selectors to have a transparent background style
fix #342

fix: prism theme update

---

sass/atoms/_code.scss
sass/atoms/_kbd.scss
sass/atoms/_pre.scss
sass/mdn-minimalist.scss

Add bottom margin to `pre` elements. This also splits out style for the `pre` and `kbd` elements into their own scss files
fix #358
fix #352

fix: margins

---

sass/atoms/_examples.scss
sass/atoms/_notecards.scss

removes top margins from examples and notecards

fix: remove missed top margins

---

sass/atoms/_notecards.scss

Update style for inline notecards with missing icons
fix #366

fix: inline notecards with missing icons

---

sass/atoms/_blockquote.scss
sass/mdn-minimalist.scss
sass/mixins/_typography.scss
sass/vars/_color-palette.scss

Add style for MDN Web Docs style blockquotes. The screenshot below for reference
fix #363

fix: blockquote style

---

sass/mixins/_typography.scss
sass/mixins/_utils.scss
test/sass/_test-mixins-utils.scss

Bump down `readable-line-length` to `75ch` and also apply to `blockquote` elements
fix #375

fix: readable line length

---

.github/dependabot.yml

There are a few actions that are still on v1 versions, so I figure this is a simpler way to get them back up-to-date

chore: Allow Dependabot bumps for GitHub Actions

---

sass/atoms/_kbd.scss

Without `white-space: nowrap`:
With `white-space: nowrap`:

Add `white-space: nowrap` to kbd element

---

sass/atoms/_examples.scss

Update `padding` and `height` for `sample-code-frame` blocks
fix #422

fix: update same-code-frame style

---

sass/atoms/_overlays.scss

Bump up the `z-index` of the `page-overlay` to `top-layer`.
fix #427

fix: page overlay stacking order

---

sass/atoms/_typography.scss
sass/mixins/_typography.scss
test/sass/_test-mixins-typography.scss

Add `slab-highlight` mixin to `typography` to allow `h3` style styling for other elements.
fix #437

feat: add slab-highlight mixin

---

sass/atoms/_notecards.scss

Add support for additional heading levels in notecards.
This adds support for headings levels 2-4 to notecards.
fix #409

fix: add support for additional heading levels

---

sass/atoms/_examples.scss

A partial solution to https://github.com/mdn/yari/issues/2683
This essentially reverts https://github.com/mdn/mdn-minimalist/pull/423
I tested this by editing the file `node_modules/@mdn/minimalist/sass/atoms/_examples.scss` in my `yari` repo and then I visited a bunch of pages that have `EmbedLiveSample`. Including
* http://localhost:3000/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator
* http://localhost:3000/en-US/docs/Web/SVG/Attribute/y2
* http://localhost:3000/en-US/docs/Web/SVG/Tutorial/Patterns
* http://localhost:3000/en-US/docs/Web/SVG/Attribute/vector-effect
* http://localhost:3000/en-US/docs/web/html/element/input/submit

don't get height on .sample-code-frame

---

sass/mixins/_utils.scss
sass/vars/_typography.scss
test/sass/_test-mixins-utils.scss

Enable a wider default readable line length. From 75ch to 85ch
fix #457

fix: wider readable line length

---

sass/atoms/_meta.scss

Remove spec badges that are added using CSS psuedo elements and only keep the text color.
Improve colour constrast for the draft and obsolete spec text.
Fix #516

fix: remove spec badges

---

sass/atoms/_links.scss

Move the external icon to the right hand side of the link
Fix #462

fix: move external icon to right

---

sass/atoms/_typography.scss
sass/mixins/_typography.scss
test/sass/_test-mixins-typography.scss

When using either the `slab-highlight` mixin or utility class, it should set the
font family to Zilla
Fix #529

fix: slab-highlight should set font-family

---

sass/atoms/_buttons-ghost.scss
sass/atoms/_buttons.scss
sass/mdn-minimalist.scss

Ensure that the ghost type button has the same initial and interactive states as common links
Fix #536

fix: ghost button interactive states

---

sass/atoms/_buttons-ghost.scss

The ghost button font color should be primary-50

fix: correct font color for ghost button

---

sass/vars/_color-palette.scss

Implement the new color variables for the v2 palette.
This does not affect the size of the library as this is only SASS variables
Fix #547

feat: color palette v2

---

sass/atoms/_tables.scss
styleguide/content/_index.md
styleguide/layouts/index.html

Give the `properties` table a base width of 100%
fix #589

fix: properties table width on tablet

---

sass/atoms/_links.scss

Fix #653.
(@schalkneethling : this is my first PR here, so it is probably not good, but let's try 😄  )

Prevent the external.svg icon to be separated from the link

---

sass/atoms/_code.scss

Hey Schalk,
it turned out a tad more complicated than I described in Slack. Namely wrapping needs to be (re-)enabled for `code` that is nested inside of a `pre` aka a lot of our code blocks.
Hope the way I did it makes sense, lmk if not!

No wrapping of inline code elements

---

dist/css/main.css
sass/vars/_mdn-web-docs-palette.scss

Uses the correct green color value for `$mdn-green100`
fix #697

fix: fix green background color

---

sass/atoms/_tables.scss
sass/vars/_mdn-web-docs-palette.scss

Fixes [#4254](https://github.com/mdn/yari/issues/4254) in `mdn/yari`

Multi-line code snippets within tables are failing contrast ratio checks for WCAG AA and AAA

---

sass/atoms/_blockquote.scss
sass/mixins/_typography.scss

To my eye at least, the current 1.25rem (desktop) and 1.125rem (mobile) font size for `<blockquote>` looks much too big — to the point of being distracting/jarring/obtrusive to readability.
I personally have found the `<blockquote>` rendering so distracting/jarring that up until now when creating MDN content, I’ve completely avoided using `<blockquote>` at all.
But now that we’re moving to Markdown, I think we’ll have a lot of contributors marking up content with "`> `" — because I think it’s relatively much more common to use in Markdown sources than `<blockquote>` is in HTML sources. And because of that, I think it’s important that we move to having `<blockquote>` content rendered in a font size that doesn’t risk being distracting and jarring to readers.
So this PR is just a strawman …

Adjust the <blockquote> font size

---

.github/workflows/auto-merge.yml

Switch to reusable auto-merge GitHub Action from `workflows`
fix #843

chore: switch to reusable auto merge

---

.github/workflows/auto-merge.yml
.github/workflows/idle-issues-pr.yml

Switch the `ref` part of the workflow string to reference the `main` branch

fix: switch ref to main branch
