mdn/mdn-minimalist

sass/atoms/_links.scss
sass/atoms/_typography.scss

Resolve failed paths when used as module

Fix paths when referenced inside module

---

sass/grid/_reference.scss
sass/mdn-minimalist.scss

Implementation of the base grid for reference pages
fix #44

(feature) reference page base grid

---

sass/atoms/_overlays.scss
sass/mdn-minimalist.scss
sass/vars/_color-palette.scss

Add styling for the page overlay element
fix #52

(enhancement) add page overlay style

---

sass/atoms/_links.scss

Code inside minimalist should no longer reference icons
fix #59

(fix) do not reference icons

---

package.json
sass/grid/_base.scss
sass/grid/_reference.scss
sass/mdn-minimalist.scss

Scope grids by page type
fix #73
Also changes npm module name to `@mdn/minimalist`
fix #67

(feature) named grids

---

sass/vars/_color-palette.scss

Add two new gray variants to the color palette
fix #78

(feature) gray variants for color palette

---

sass/vars/_color-palette.scss

Add standard linear gradient for backgrounds
fix #87

standard linear gradient

---

sass/mdn-minimalist.scss
sass/vars/_layout.scss
sass/vars/_spacing.scss

Rename the spacing SASS file to layout and add base layout units
fix #89

rename spacing to layout

---

sass/atoms/_forms.scss
sass/mixins/_typography.scss
sass/vars/_typography.scss

Improved naming of typography scale. Defined type scale for mobile as well as desktop/tablet
fix #91

better typography naming

---

sass/atoms/_icons.scss
sass/vars/_layout.scss

Small updates to layout variables and the icon class
fix #94

layout vars and icon class update

---

sass/grid/_base.scss
sass/grid/_reference.scss
sass/mdn-minimalist.scss

Change reference page grid to accomodate page content container element
fix #96

update to reference page grid

---

sass/grid/_reference.scss

Update to reference page grid
fix #98

small reference grid update

---

sass/grid/_reference.scss
sass/vars/_layout.scss

small changes to variables and grid

---

sass/atoms/_code.scss
sass/mdn-minimalist.scss
sass/vars/_borders.scss

Add style for code examples
fix #111

style for code examples

---

sass/mixins/_utils.scss
tests/sass/_test-mixins-utils.scss

Add reset list util mixin
fix #117

add reset list util mixin

---

.github/workflows/test.yml
.vscode/settings.json
package.json
sass/atoms/_typography.scss
webpack.config.js
yarn.lock

Build minimalist using Webpack so we can match the build style of Yari
fix #124

add webpack for builds

---

sass/atoms/_code.scss
sass/grid/_reference.scss
sass/mixins/_utils.scss
sass/vars/_layout.scss
sass/vars/_typography.scss
test/sass/_test-mixins-utils.scss

Set a base unit variable of `6px` as `$base-unit`

various small tweaks. Set base unit variable

---

.stylelintrc.json
package.json
sass/atoms/_buttons.scss

Change icon button class from `icon` to `icon-button`
fix #132

breaking: fix icon button

---

sass/atoms/_tables.scss
sass/mdn-minimalist.scss

Add standard table styles
Part of #147

standard table style

---

.stylelintrc.json
sass/atoms/_tables.scss
sass/atoms/_typography.scss
sass/mixins/_utils.scss
test/sass/_test-mixins-utils.scss

Updates table styles to include properties tables
Part of #147

table styles v2

---

.stylelintignore
sass/atoms/_tables.scss

Add small white borders to the standard table cells
Part of #147

white border to standard table

---

sass/atoms/_tables.scss

Final table tweak

---

.github/workflows/test.yml
sass/atoms/_base.scss
sass/atoms/_links.scss
sass/atoms/_lists.scss
sass/atoms/_overlays.scss
sass/atoms/_tables.scss
sass/atoms/_typography.scss
sass/mdn-minimalist.scss
sass/molecules/_article.scss
sass/shared-variables.module.scss
sass/vars/_color-palette.scss

First stage of typography updates.
This also includes some tweaks to the colors for tables.
Part of #153

typography

---

sass/atoms/_tables.scss
sass/molecules/_article.scss

Additional typography adjustments.
Possible final changes to property and standard tables
Part of #153

typography and tables

---

sass/atoms/_tables.scss
sass/shared-variables.module.scss
sass/vars/_color-palette.scss

Remove primary-600
Reduce padding on cells for property tables

color and table

---

sass/atoms/_examples.scss
sass/atoms/_tables.scss
sass/mdn-minimalist.scss
sass/vars/_borders.scss
sass/vars/_layout.scss

Cleanup border and define sample code component style.
fix #181

sample code component style

---

sass/atoms/_tables.scss

mobile table style updates

---

sass/grid/_reference.scss

fix: grid layout update

---

sass/grid/_reference.scss
sass/vars/_layout.scss

Update reference grid to allow for correct alignment of all page sections.
fix #189

update to reference grid

---

sass/atoms/_icons.scss

feat: add non-standard class

---

package.json
yarn.lock

Add bundlesize to keep tabs on minimalist's bundlesize over time.
fix #54

deps: keep tabs on bundlesize

---

package.json
sass/atoms/_code.scss
sass/atoms/_tables.scss
sass/vars/_borders.scss
sass/vars/_color-palette.scss

Add styling for `kbd` elements
fix #232

fix: kbd element

---

package.json
sass/atoms/_notecards.scss
sass/mdn-minimalist.scss
sass/vars/_borders.scss
sass/vars/_color-palette.scss
webpack.config.js
yarn.lock

Add styles for the various notecards used on MDN
fix #239

fix: notecards

---

sass/atoms/_notecards.scss
sass/vars/_typography.scss

Add support for inline notecards.

fix: inline notecards

---

sass/atoms/_notecards.scss

Add top and bottom margin to all notecards

fix: notecard update

---

sass/grid/_standard.scss
sass/mdn-minimalist.scss

Add standard grid template style
fix #248

fix: add standard grid

---

sass/atoms/_meta.scss
sass/atoms/_notecards.scss
sass/mdn-minimalist.scss
sass/utils/_utils.scss
sass/vars/_color-palette.scss

Add style for relevant specification and inline badges
fix #255

fix: meta badges

---

sass/atoms/_callout.scss
sass/mdn-minimalist.scss

Add style for callouts such as those used on the Learn pages.
fix #271

feat: add callout style

---

sass/atoms/_notecards.scss

Add style for a success type notecard
fix #270

feat: success notecard

---

.gitignore
sass/atoms/_code.scss

Add style for good and bad code example blocks
fix #280

fix: good and bad code examples

---

sass/atoms/_links.scss
sass/mdn-minimalist.scss
sass/mixins/_links.scss
test/sass/_test-mixins-links.scss

Add mixin and utility class for highlighted link states
fix #286

feat: highlighted link state

---

sass/atoms/_primsjs.scss
sass/mdn-minimalist.scss

Minimal overrides to improve the accessibility of our Prismjs theme
fix #321

fix: prismjs theme

---

.github/workflows/release-please.yml

fix: release please

---

sass/atoms/_buttons.scss
sass/mdn-minimalist.scss
sass/mixins/_buttons.scss
sass/vars/_shadows.scss
test/sass/_test-mixins-buttons.scss

Update the interaction states of buttons.
fix #320

fix: button interaction states

---

sass/mixins/_animation.scss

Add slow pulsing animation for use with loading screen
fix #332

feat: slow pulse animation

---

sass/vars/_typography.scss

Switch to a smaller type scale for mobile devices
fix #339

fix: switch to small type scale - mobile

---

sass/atoms/_tables.scss
sass/vars/_borders.scss

Update colors for properties table to ensure correct color contrast
fix #351

fix: update to properties table color

---

sass/vars/_borders.scss

Update pre element border color to `primary-50`
fix #365

fix: update pre element border color

---

sass/atoms/_callout.scss

Update style for `callout` type.
fix #415

fix: callout style update

---

sass/atoms/_tables.scss

Please test on a mobile device since i can't since i done the change from my mobile device 🤷🏻‍♂️
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x

Attempt to fix table overflow-x

---

.github/workflows/welcome.yml

Add first-interaction action to greet new contributors
fix #395

fix: add first interaction action

---

sass/atoms/_notecards.scss
sass/mdn-minimalist.scss
sass/mixins/_notecards.scss
test/sass/_test-mixins-notecards.scss
test/sass/test.scss

- fix: no need for h2 in notecards
- chore: improve notecards through mixins
Thanks, @Ryuno-Ki for the suggestion.

470 no need for notecard h2

---

package.json

Add explicit yarn build target for styleguide

chore: add styleguide build target

---

README.md

Add Netlify deploy badge to README

chore: add netlify badge to readme

---

.github/workflows/welcome.yml

Fix loud welcome messages
fix #480

chore: loud welcome message fix

---

sass/atoms/_blockquote.scss
sass/atoms/_buttons.scss
sass/atoms/_code.scss
sass/atoms/_examples.scss
sass/atoms/_icons.scss
sass/atoms/_kbd.scss
sass/atoms/_links.scss
sass/atoms/_meta.scss
sass/atoms/_tables.scss
sass/shared-variables.module.scss
sass/vars/_borders.scss
sass/vars/_layout.scss
styleguide/assets/molecules/_toc.scss
styleguide/assets/organisms/_footer.scss

Switch to using math.div in SASS
fix #629

fix: switch to math.div

---

sass/vars/_color-gradients.scss

Change the `to` color for the light gray gradient.
fix #688

fix: change light gray gradient

---

sass/atoms/_meta.scss
styleguide/content/meta/_index.md
styleguide/layouts/partials/main-nav.html

- remove the left border from inline spec badges
- add additional left and right padding
fix #691

fix: change spec badges

---

sass/atoms/_tables.scss

remove border-left property for th,td :first-child

---

README.md

Update README.md to include note that installing Hugo is a pre-req before running locally

---

.github/workflows/auto-merge.yml

Add auto-merge actions for dependabot pull requests that bumps the minor version
fix #828

chore: add auto merge

---

.github/workflows/auto-merge.yml

update to auto merge workflow

---

.github/workflows/idle-issues-pr.yml

Add the stale issue and pr workflow from `/workflows`
fix #841

chore: reuse stale issue and pr workflow

---

.github/workflows/auto-merge.yml

Fix formatting of `auto-merge`

fix: auto-merge

---

.github/workflows/idle-issues-pr.yml

Temporarily change the cron time for stale action

chore: temporarily change cron time for stale

---

.github/workflows/build-dist.yml
.github/workflows/build.yml

Switch to using the reusable release please action from `mdn/workflows`
fix #860

chore: switch to reusable release please
